services:
  backend:
    build: ./spring-backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./react-frontend
    env_file:
      - ./react-frontend/.env
    ports:
      - "3000"
    volumes:
      - ./react-frontend/src:/app/src
      - ./react-frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
       - mysql_data:/var/lib/mysql
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 7s
      retries: 10
    networks:
      - app-network
  
  nginx-proxy:
    build: ./nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    env_file:
      - .env.nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
    app-network: 
      driver: bridge